# Generated by Django 4.0.3 on 2022-04-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_class_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='ext_description',
        ),
        migrations.AlterField(
            model_name='class',
            name='school',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='caption',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='is_stats_processed',
            field=models.BooleanField(default=False),
        ),
    ]
