# Generated by Django 4.0.3 on 2022-04-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_remove_questionnaire_ext_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='message_to_students',
            field=models.TextField(null=True),
        ),
    ]
