# Generated by Django 4.0.3 on 2022-05-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_questionnaire_message_to_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='personal_questionnaire_link',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
