# Generated by Django 4.0.3 on 2022-05-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_student_personal_questionnaire_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='personal_questionnaire_link',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
