# Generated by Django 4.0.3 on 2022-05-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_alter_grade_svg_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='svg_icon',
        ),
    ]
