# Generated by Django 4.0.3 on 2022-03-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='int_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
