# Generated by Django 4.0.3 on 2022-03-28 15:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_grade_int_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='grade',
            name='txt_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
