# Generated by Django 4.0.3 on 2022-04-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_grade_bg_color_alter_grade_txt_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='created_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class2created_from', to='teacher.class'),
        ),
    ]
