# Generated by Django 4.0.3 on 2022-05-02 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_alter_student_personal_questionnaire_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire2class', to='teacher.class', unique=True),
        ),
    ]
