# Generated by Django 4.0.3 on 2022-05-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_questionnaire_classid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='questionnaire_response_rate',
            field=models.IntegerField(default=0),
        ),
    ]
