# Generated by Django 4.0.3 on 2022-05-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_student_questionnaire_fillin_ratio'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('grading_student', 'graded_student'), name='unique grading to graded'),
        ),
    ]
