# Generated by Django 4.0.3 on 2022-05-17 10:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_answer_unique grading to graded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='txt_color',
        ),
        migrations.AlterField(
            model_name='grade',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#888888', image_field=None, max_length=18, samples=None),
        ),
    ]
