# Generated by Django 4.0.3 on 2022-05-21 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_remove_grade_txt_color_alter_grade_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer2grade', to='teacher.grade'),
        ),
    ]
