# Generated by Django 4.0.3 on 2022-05-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_alter_answer_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='svg_icon',
            field=models.TextField(null=True),
        ),
    ]
