# Generated by Django 4.0.3 on 2022-05-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_grade_svg_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='caption',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='caption',
            new_name='name',
        ),
    ]
